# integration tests for Qwik ecosystem projects - scheduled or manual run for all suites
name: qwik-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  # Disable incremental build, speeds up CI
  CARGO_INCREMENTAL: 0

on:
  schedule:
    - cron: "0 5 * * 1,3,5" # monday,wednesday,friday 5AM
  workflow_dispatch:
    inputs:
      refType:
        description: "type of ref"
        required: true
        type: choice
        options:
          - branch
          - tag
          - commit
          - release
        default: "branch"
      ref:
        description: "qwik ref to use"
        required: true
        type: string
        default: "main"
      repo:
        description: "qwik repository to use"
        required: true
        type: string
        default: "QwikDev/qwik"
  repository_dispatch:
    types: [ecosystem-ci]
jobs:
  test-ecosystem:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - qwik-ui-headless
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        id: setup-node
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts
          --${{ inputs.refType || github.event.client_payload.refType || 'branch' }} ${{ inputs.ref || github.event.client_payload.ref || 'main' }}
          --repo ${{ inputs.repo || github.event.client_payload.repo || 'QwikDev/qwik' }}
          ${{ matrix.suite }}
        id: ecosystem-ci-run
